version: '3'

services:
  cliente:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT = 3000
      - MONGO_DB_CNN = mongodb://mongo:27017/Bares
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null