version: '3'

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    